version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config

jobs:
 build:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Run Affected Builds
          command: yarn nx affected --target=build --base=main
      - run:
          name: Run Affected Unit Tests
          command: yarn nx affected --target=test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git 

workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy

